2017-12-24 15:44:44,763 - UserController - 2896 - ERROR - execute_get - Traceback (most recent call last):
  File "C:\python27\lib\site-packages\src-0.0.1-py2.7.egg\src\main\master\controller\UserController.py", line 36, in execute_get
    return tasks[task_name]()
  File "C:\python27\lib\site-packages\src-0.0.1-py2.7.egg\src\main\master\controller\UserController.py", line 34, in <lambda>
    'get_user_info_by_user_id' : lambda : self.get_user_info_by_user_id(),
  File "C:\python27\lib\site-packages\src-0.0.1-py2.7.egg\src\main\master\controller\UserController.py", line 66, in get_user_info_by_user_id
    hello = self.get_argument('hello')
  File "C:\python27\lib\site-packages\tornado\web.py", line 404, in get_argument
    return self._get_argument(name, default, self.request.arguments, strip)
  File "C:\python27\lib\site-packages\tornado\web.py", line 481, in _get_argument
    raise MissingArgumentError(name)
MissingArgumentError: HTTP 400: Bad Request (Missing argument hello)

2017-12-24 15:49:26,640 - UserController - 6880 - ERROR - execute_get - Traceback (most recent call last):
  File "C:\python27\lib\site-packages\src-0.0.1-py2.7.egg\src\main\master\controller\UserController.py", line 36, in execute_get
    return tasks[task_name]()
  File "C:\python27\lib\site-packages\src-0.0.1-py2.7.egg\src\main\master\controller\UserController.py", line 34, in <lambda>
    'get_user_info_by_user_id' : lambda : self.get_user_info_by_user_id(),
  File "C:\python27\lib\site-packages\src-0.0.1-py2.7.egg\src\main\master\controller\UserController.py", line 66, in get_user_info_by_user_id
    hello = self.get_argument('hello')
  File "C:\python27\lib\site-packages\tornado\web.py", line 404, in get_argument
    return self._get_argument(name, default, self.request.arguments, strip)
  File "C:\python27\lib\site-packages\tornado\web.py", line 481, in _get_argument
    raise MissingArgumentError(name)
MissingArgumentError: HTTP 400: Bad Request (Missing argument hello)

2017-12-24 15:50:19,668 - UserController - 2836 - ERROR - execute_get - Traceback (most recent call last):
  File "C:\python27\lib\site-packages\src-0.0.1-py2.7.egg\src\main\master\controller\UserController.py", line 36, in execute_get
    return tasks[task_name]()
  File "C:\python27\lib\site-packages\src-0.0.1-py2.7.egg\src\main\master\controller\UserController.py", line 34, in <lambda>
    'get_user_info_by_user_id' : lambda : self.get_user_info_by_user_id(),
  File "C:\python27\lib\site-packages\src-0.0.1-py2.7.egg\src\main\master\controller\UserController.py", line 66, in get_user_info_by_user_id
    hello = self.get_argument('hello')
  File "C:\python27\lib\site-packages\tornado\web.py", line 404, in get_argument
    return self._get_argument(name, default, self.request.arguments, strip)
  File "C:\python27\lib\site-packages\tornado\web.py", line 481, in _get_argument
    raise MissingArgumentError(name)
MissingArgumentError: HTTP 400: Bad Request (Missing argument hello)

2017-12-24 16:14:07,973 - UserController - 6284 - ERROR - execute_get - Traceback (most recent call last):
  File "C:\python27\lib\site-packages\src-0.0.1-py2.7.egg\src\main\master\controller\UserController.py", line 38, in execute_get
    self.write(json.dumps(tasks[task_name]()))
  File "C:\python27\lib\json\__init__.py", line 244, in dumps
    return _default_encoder.encode(obj)
  File "C:\python27\lib\json\encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\python27\lib\json\encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "C:\python27\lib\json\encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: <src.main.master.entity.DataResult.DataResult object at 0x02FAA3F0> is not JSON serializable

2017-12-24 16:14:13,533 - UserController - 6284 - ERROR - execute_get - Traceback (most recent call last):
  File "C:\python27\lib\site-packages\src-0.0.1-py2.7.egg\src\main\master\controller\UserController.py", line 38, in execute_get
    self.write(json.dumps(tasks[task_name]()))
  File "C:\python27\lib\json\__init__.py", line 244, in dumps
    return _default_encoder.encode(obj)
  File "C:\python27\lib\json\encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\python27\lib\json\encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "C:\python27\lib\json\encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: <src.main.master.entity.DataResult.DataResult object at 0x0360B3D0> is not JSON serializable

2017-12-24 16:14:55,526 - UserController - 7068 - ERROR - execute_get - Traceback (most recent call last):
  File "C:\python27\lib\site-packages\src-0.0.1-py2.7.egg\src\main\master\controller\UserController.py", line 38, in execute_get
    self.write(json.dumps(tasks[task_name]()))
  File "C:\python27\lib\json\__init__.py", line 244, in dumps
    return _default_encoder.encode(obj)
  File "C:\python27\lib\json\encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\python27\lib\json\encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "C:\python27\lib\json\encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: <src.main.master.entity.DataResult.DataResult object at 0x0360B1D0> is not JSON serializable

2017-12-24 16:15:03,683 - UserController - 6284 - ERROR - execute_get - Traceback (most recent call last):
  File "C:\python27\lib\site-packages\src-0.0.1-py2.7.egg\src\main\master\controller\UserController.py", line 38, in execute_get
    self.write(json.dumps(tasks[task_name]()))
KeyError: u'get_user_info_by_'

2017-12-24 16:15:26,125 - UserController - 3620 - ERROR - execute_get - Traceback (most recent call last):
  File "C:\python27\lib\site-packages\src-0.0.1-py2.7.egg\src\main\master\controller\UserController.py", line 38, in execute_get
    self.write(json.dumps(tasks[task_name]()))
  File "C:\python27\lib\json\__init__.py", line 244, in dumps
    return _default_encoder.encode(obj)
  File "C:\python27\lib\json\encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\python27\lib\json\encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "C:\python27\lib\json\encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: <src.main.master.entity.DataResult.DataResult object at 0x0360BDB0> is not JSON serializable

2017-12-24 16:24:48,549 - UserController - 6980 - ERROR - execute_get - Traceback (most recent call last):
  File "C:\python27\lib\site-packages\src-0.0.1-py2.7.egg\src\main\master\controller\UserController.py", line 38, in execute_get
    self.write(json.dumps(tasks[task_name]().__dict__))
KeyError: u'get_user_info_by_user'

2017-12-24 20:52:13,740 - UserController - 7424 - ERROR - execute_get - Traceback (most recent call last):
  File "C:\python27\lib\site-packages\src-0.0.1-py2.7.egg\src\main\master\controller\UserController.py", line 39, in execute_get
    self.write(json.dumps(tasks[task_name]().__dict__))
KeyError: u'get_user_info_by_user_id'

2017-12-24 20:52:39,530 - UserController - 7424 - ERROR - execute_get - Traceback (most recent call last):
  File "C:\python27\lib\site-packages\src-0.0.1-py2.7.egg\src\main\master\controller\UserController.py", line 39, in execute_get
    self.write(json.dumps(tasks[task_name]().__dict__))
  File "C:\python27\lib\site-packages\src-0.0.1-py2.7.egg\src\main\master\controller\UserController.py", line 37, in <lambda>
    'get_user_info_by_user_name' : lambda : self.get_user_info_by_user_name()
  File "C:\python27\lib\site-packages\src-0.0.1-py2.7.egg\src\main\master\controller\UserController.py", line 74, in get_user_info_by_user_name
    userName = self.get_argument('userName')
  File "C:\python27\lib\site-packages\tornado\web.py", line 404, in get_argument
    return self._get_argument(name, default, self.request.arguments, strip)
  File "C:\python27\lib\site-packages\tornado\web.py", line 481, in _get_argument
    raise MissingArgumentError(name)
MissingArgumentError: HTTP 400: Bad Request (Missing argument userName)

2017-12-24 21:24:31,707 - UserController - 7696 - ERROR - execute_get - Traceback (most recent call last):
  File "C:\python27\lib\site-packages\src-0.0.1-py2.7.egg\src\main\master\controller\UserController.py", line 39, in execute_get
    self.write(json.dumps(tasks[task_name]().__dict__))
  File "C:\python27\lib\json\__init__.py", line 244, in dumps
    return _default_encoder.encode(obj)
  File "C:\python27\lib\json\encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\python27\lib\json\encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "C:\python27\lib\json\encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: datetime.datetime(2017, 12, 24, 21, 24, 23) is not JSON serializable

2018-04-09 14:36:34,760 - UserController - 5640 - ERROR - add_user_info - {
"userName":"test_user1",
"userPasswd":"123456",
"remarks":""
}
2018-04-09 14:36:34,760 - UserController - 5640 - ERROR - add_user_info - JJJJJJJJJJJasssss
2018-04-09 14:53:48,859 - UserController - 5640 - ERROR - add_user_info - {"userName":"testtesttest","userPasswd":"12345"}
2018-04-09 14:53:48,859 - UserController - 5640 - ERROR - add_user_info - JJJJJJJJJJJasssss
2018-04-09 14:54:58,454 - UserController - 15816 - ERROR - add_user_info - {"userName":"test_user3","userPasswd":"123456"}
2018-04-09 14:54:58,456 - UserController - 15816 - ERROR - add_user_info - JJJJJJJJJJJasssss
2018-04-09 15:00:35,835 - UserController - 5640 - ERROR - add_user_info - {"userName":"test_user4","userPasswd":"123456"}
2018-04-09 15:00:35,835 - UserController - 5640 - ERROR - add_user_info - JJJJJJJJJJJasssss
2018-04-09 15:03:10,881 - UserController - 14968 - ERROR - add_user_info - {"userName":"testuseruser","userPasswd":"123456"}
2018-04-09 15:03:10,882 - UserController - 14968 - ERROR - add_user_info - JJJJJJJJJJJasssss
2018-04-09 15:29:19,161 - UserController - 15816 - ERROR - add_user_info - {"userName":"1234567","userPasswd":"1234567"}
2018-04-09 15:29:19,161 - UserController - 15816 - ERROR - add_user_info - JJJJJJJJJJJasssss
